"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@components/Header";
import Footer from "@components/Footer";
import { Suspense, useEffect, useState } from "react";
import { NavigationEvents } from "@/components/NavigationEvent";
import { Helmet } from "react-helmet";
import { usePathname, useSearchParams } from "next/navigation";
import Reloading from "@/components/Reloading";

const inter = Inter({ subsets: ["latin"] });
// export const metadata = {
//   title: "Câu lạc bộ lập trình FU-DEVER",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 2300);
    setIsLoading(true);
  }, [pathname, searchParams]);  

  return (
    <html lang="en">
      <body className={inter.className}>
        <Helmet>
          <title>Câu lạc bộ lập trình FU-DEVER</title>
          <meta name="description" content="Generated by create next app" />
        </Helmet>
        <Suspense fallback={null}>
          {isLoading ? <Reloading/> : null}
        </Suspense>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
