"use client";
import Header from "@components/Header";
import Footer from "@components/Footer";
import { Helmet } from "react-helmet";
import { useEffect, useState } from "react";
import Reloading from "@/components/Reloading";
import ToastNotificationComp from "@/components/ToastNotificationComp";

const MainLayout = ({ children }: { children: React.ReactNode }) => {
  const [isLoading, setIsloading] = useState(true);

  useEffect(() => {
    const loadingTimeout = setTimeout(() => {
      setIsloading(false);
    }, 2000);

    const minimumLoadingTime = 2000;
    const additionalTime = minimumLoadingTime - 2000;
    if (additionalTime > 0) {
      setTimeout(() => {
        setIsloading(false);
      }, additionalTime);
    }

    return () => {
      clearTimeout(loadingTimeout);
    };
  }, []);
  const ogImageUrl =
    "https://res.cloudinary.com/dy1uuo6ql/image/upload/v1694673083/vixsfn8yhriheyftynyd.png";
  const ogImageType = "image/png";
  const ogImageWidth = "1200";
  const ogImageHeight = "600";
  return (
    <>
      <Helmet>
        <title>Câu lạc bộ lập trình FU-DEVER</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:image" content={ogImageUrl} />
        <meta property="og:image:type" content={ogImageType} />
        <meta property="og:image:width" content={ogImageWidth} />
        <meta property="og:image:height" content={ogImageHeight} />
      </Helmet>
      {isLoading ? <Reloading /> : null}
      <Header></Header>
      {children}
      <ToastNotificationComp />
      <Footer></Footer>
    </>
  );
};

export default MainLayout;
